label:
  swe: Moderna
  eng: Modern
order: 10
folders:
  fisk:
    title:
      swe: Finlandssvenska texter
      eng: Finland Swedish
    description: Det första steget för att skapa en finlandssvensk korpus togs redan på 1990-talet (Institutionen för nordiska språk vid Helsingfors universitet) och under åren 1999–2000 fortsatte arbetet (ett samarbetsprojekt mellan Institutet för de inhemska språken, Institutionen för allmän språkvetenskap och CSC (IT Center for Science)). Under åren 2011–2013 byggs den finlandssvenska korpusen ut som ett samarbetsprojekt mellan Svenska litteratursällskapet i Finland, Institutet för de inhemska språken och Göteborgs universitet.
    subfolders:
      governmental:
        title:
          swe: Myndighetstexter
          eng: Governmental texts
      literature:
        title:
          swe: Skön- och facklitteratur
          eng: Fiction and non-fiction literature
      magazines:
        title:
          swe: Tidskrifter
          eng: Journals
      newstexts:
        title:
          swe: Tidningstexter
          eng: Newspaper texts
        subfolders:
          abounderrattelser:
            description: <a href="www.abounderrattelser.fi" target="_blank">Åbo Underrättelser</a> är en regional svenskspråkig dagstidning i Åbotrakten.
            title: Åbo Underrättelser
          fnb:
            description: <a href="http://www.stt.fi/sv" target="_blank">FNB</a> är Finlands ledande nyhets- och bildbyrå.
            title: FNB
          hbl:
            description: <a href="http://www.hbl.fi" target="_blank">Hufvudstadsbladet</a> är den största finlandssvenska dagstidningen i Finland.
            title: Hufvudstadsbladet
          jakobstadstidning:
            description: Jakobstads Tidning var en lokal dagstidning i Österbotten som gavs ut under perioden 1898–2008.
            title: Jakobstads tidning
          osterbottenstidning:
            description: <a href="http://www.ot.fi" target="_blank">Österbottens Tidning</a> är en regional svenskspråkig tidning i Österbotten.
            title: Österbottens Tidning
          pargaskungorelser:
            description: <a href="http://www.pku.fi" target="_blank">Pargas Kungörelser</a> är en regional tvåspråkig (svenska och finska) tidning med spridning i Pargas med omnejd. I korpusen är endast den svenskspråkiga delen av tidningen med.
            title: Pargas kungörelser
          sydosterbotten:
            description: <a href="http://www.sydin.fi" target="_blank">Syd-Österbotten</a> är en regional svenskspråkig dagstidning i Österbotten.
            title: Syd-Österbotten
          vasab:
            description: <a href="http://www.vasabladet.fi" target="_blank">Vasabladet</a> är en regional svenskspråkig dagstidning i Österbotten.
            title: Vasabladet
      webtexts:
        title:
          swe: Webbtexter
          eng: Web texts
  governmental:
    title:
      swe: Myndighetstexter
      eng: Governmental texts
    subfolders:
      tvakammarriksdagen:
        title:
          swe: Tvåkammarriksdagen
          eng: Bicameral Riksdag
        description:
          swe: |-
            <b>Samling av textdokument från Tvåkammarriksdagen</b><br><br>
            Denna resurs innehåller en samling textdokument från svenska Tvåkammarriksdagen.
            Den är indelad i olika kategorier(t.ex. motioner, protokoll,
            register etc.) och har annoterats med olika ord- och dokumentnivåattribut.
            Varje kategori är tillgänglig för nedladdning som en zippad fil.
          eng: |-
            <b>Collection of textual documents from the Swedish bicameral parliament data</b><br><br>
            This resource contains a collection of textual documents from the Swedish
            bicameral parliament data. It is is divided into various categories
            (e.g. motions, protocols, registers, ect.) and have been annotated with
            various word and document level attributes. Each category is available
            for download as a zipped file.
      rd:
        title: Riksdagens öppna data
        description:
          swe: Data från <a href="https://data.riksdagen.se/data/dokument/" target="_blank">data.riksdagen.se/data/dokument/</a> insamlat 2022.
          eng: The data was collected from <a href="data.riksdagen.se/data/dokument/"target="_blank">data.riksdagen.se/data/dokument/</a> in 2022 and is subject to updates.
  l2:
    title:
      swe: L2-Korp
      eng: L2 Korp
  magazines:
    title:
      swe: Tidskrifter
      eng: Journals
  medical:
    title:
      swe: Medicinska texter
      eng: Medical texts
    subfolders:
      ltd:
        title: Läkartidningen
  newstexts:
    title:
      swe: Nyhetstexter
      eng: News texts
    subfolders:
      gp:
        title: Göteborgs-Posten
      press:
        title: Press
      webnews:
        title:
          swe: Webbnyheter
          eng: Web news
      svtnews:
        title: SVT nyheter
  novels:
    title:
      swe: Skönlitteratur
      eng: Fiction
  protected:
    title:
      swe: Skyddade korpusar
      eng: Protected corpora
  socialmedia:
    title:
      swe: Sociala medier
      eng: Social media
    subfolders:
      bloggmix:
        description:
          swe: Material från ett urval av svenska bloggar. Uppdateras regelbundet.
          eng: Texts from a selection of Swedish blogs. Is continually updated.
        title:
          swe: Bloggmix
          eng: Blog mix
      forum:
        title:
          swe: Diskussionsforum
          eng: Internet forums
        subfolders:
          familjeliv:
            description:
              swe: Material från diskussionsforumet <a target="_blank" href="https://www.familjeliv.se/">Familjeliv</a>. Uppdateras årligen.
              eng: Texts from the internet forum <a target="_blank" href="https://www.familjeliv.se/">Familjeliv</a>. Is continually updated.
            title: Familjeliv
          flashback:
            description:
              swe: Material från diskussionsforumet <a target="_blank" href="https://www.flashback.org/">Flashback</a>. Uppdateras årligen.
              swe: Texts from the internet forum <a target="_blank" href="https://www.flashback.org/">Flashback</a>. Is continually updated.
            title: Flashback
      twitter:
        title: Twitter
  strindberg:
    title: August Strindberg
  sweac:
    title:
      swe: Akademiska texter
      eng: Akademic texts
map_enabled: true
preselected_corpora:
   - __newstexts.svtnews
   - attasidor
   - da
#  - suc3
#  - wikipedia-sv
#  - talbanken
#  - sfs
#  - snp7879
#  - __newstexts
#  - __fisk
#  - fof
#  - twitter
#  - __socialmedia.bloggmix
#  - romi
#  - romii
#  - rom99
#  - storsuc
